### ISSUE TITLE
有个模块识别不了

### ISSUE THREAD

**Issue by Strange0cookies** [liuxiyang641/RAGAT#11]
请问您的代码包里helper.py里import的ordered-set是哪个版本，我安装了几个版本以后运行，一直提示module not found

**Comment by liuxiyang641** [comment]
你好，时间过去的比较久，具体的实验环境我找不到了。
你是直接用pip安装的吗？[ordered-set](https://pypi.org/project/ordered-set/)
我印象中这个模块直接按照默认的安装命令就可以装好，没有发现太多的冲突

**Comment by Strange0cookies** [comment]
我用conda安装的，然后尝试了好几个版本，就pycharm能识别到这个模块，但是代码运行的时候一直报错，说模块找不到。我最近开始研究gnn模型，正好看到你的论文，所以想问问看你有没有遇到过类似的问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 晚上7:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuxiyang641/RAGAT] 有个模块识别不了 (Issue #11)





 
你好，时间过去的比较久，具体的实验环境我找不到了。
 你是直接用pip安装的吗？ordered-set
 我印象中这个模块直接按照默认的安装命令就可以装好，没有发现太多的冲突

**Comment by liuxiyang641** [comment]
抱歉，我之前没有遇到过类似的问题。模块找不到的原因能排除是运行环境的设置问题吗？比如安装的时候有没有安装正确的conda环境中，或者pycharm启动的时候指定的环境是否正确？

**Comment by Strange0cookies** [comment]
我是学机械的，对于环境这块不太了解，但是看配置应该是有的，你看看我这个环境是不是对的？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuxiyang641/RAGAT] 有个模块识别不了 (Issue #11)





 
抱歉，我之前没有遇到过类似的问题。模块找不到的原因能排除是运行环境的设置问题吗？比如安装的时候有没有安装正确的conda环境中，或者pycharm启动的时候指定的环境是否正确？

**Comment by liuxiyang641** [comment]
可以，要不你发一下截图？看一下conda环境和安装的包

**Comment by Strange0cookies** [comment]
今天有点晚了，就不打扰你了。明早我去我的工位上截图发给你



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 晚上10:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuxiyang641/RAGAT] 有个模块识别不了 (Issue #11)





 
可以，要不你发一下截图？看一下conda环境和安装的包

**Comment by liuxiyang641** [comment]
好

**Comment by Strange0cookies** [comment]
我建立的这个虚拟环境是基于python3.7.6，安装的包如下：










------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 晚上10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuxiyang641/RAGAT] 有个模块识别不了 (Issue #11)





 
好

**Comment by liuxiyang641** [comment]
你好，我这里无法看到你的图片或者其它关于安装包的说明。
我看到你是通过邮件回复的，要不尝试直接在github上回复？

**Comment by Strange0cookies** [comment]
![image](https://user-images.githubusercontent.com/100328275/233921323-e499e461-076e-4c40-8af8-06916c9ca557.png)
![image](https://user-images.githubusercontent.com/100328275/233921393-12816148-9cfb-42b5-8952-c17c5e29e5ff.png)
你看一下，这样能看到吗

**Comment by liuxiyang641** [comment]
看起来是有安装的，你是在这个env1环境下运行的吗？

**Comment by Strange0cookies** [comment]
是的，我以为是那个模块版本的问题，我用conda换了几个版本也这样，所以很奇怪

**Comment by liuxiyang641** [comment]
可以提供下运行结果输出的截图吗？最好包括启动的命令

**Comment by Strange0cookies** [comment]
直接运行run.py是这样的，我看csdn上有一个案例说是log文件夹里缺少文件会导致这样
![image](https://user-images.githubusercontent.com/100328275/233980038-1e4e36e3-ecc4-4b7a-b9fe-c5e4708819ac.png)
在终端运行这条命令：python run.py -epoch 1500 -name test_fb -model ragat -score_func \
就会显示找不到模块
![image](https://user-images.githubusercontent.com/100328275/233980221-7b00ef0c-8855-46a0-92e1-8408c65e192b.png)

**Comment by liuxiyang641** [comment]
直接运行`run.py`文件没有指定一些运行命令的话可能会出错。后面这张图片我没看到运行环境是哪个？能够确定是在`env1`环境中运行的命令吗？

**Comment by liuxiyang641** [comment]
另外你这个命令输入全了吗？完整的命令应该是：
```bash
python run.py -epoch 1500 -name test_fb -model ragat -score_func \
interacte -opn cross -gpu 0 -data FB15k-237 -gcn_drop 0.4 -ifeat_drop 0.4 \
-ihid_drop 0.3 -batch 1024 -iker_sz 9 -attention True -head_num 2
```
要全部输入后运行

**Comment by Strange0cookies** [comment]
全部输入以后似乎也不太行
![image](https://user-images.githubusercontent.com/100328275/234202311-50d190b5-f61c-410d-9c93-838880e8b636.png)

**Comment by liuxiyang641** [comment]
这样输入是错误的，需要在一行内输入所有的命令，`\`是表示换行的意思。试一试下面的命令：
```bash
python run.py -epoch 1500 -name test_fb -model ragat -score_func interacte -opn cross -gpu 0 -data FB15k-237 -gcn_drop 0.4 -ifeat_drop 0.4 -ihid_drop 0.3 -batch 1024 -iker_sz 9 -attention True -head_num 2
```

**Comment by liuxiyang641** [comment]
在输入命令前检查下自己的`conda`环境是不是在`env1`下，输入命令`conda env list`检查下

**Comment by Strange0cookies** [comment]
好奇怪，还是识别不到这个包，我自己再研究研究吧，谢谢指导
![image](https://user-images.githubusercontent.com/100328275/234294183-d2fc3335-a31f-4815-b190-6e65dfafb187.png)

**Comment by liuxiyang641** [comment]
我仔细检查了下，原因应该是安装错包了，应该`pip install ordered_set`，你安装的是`ordered-set`
