### ISSUE TITLE
Reported results

### ISSUE THREAD

**Issue by parsa-abbasi** [liuxiyang641/RAGAT#12]
Hello,
I have a question regarding the strategy parameter in the code. Specifically, I'm not sure which strategy was used to obtain the results reported in _Table 2_ of the RAGAT paper.

From the code, I see that the default value for the strategy parameter is `one-to-n`. Does this mean that the results reported in _Table 2_ were obtained using the `one-to-n` strategy?

I would greatly appreciate it if you could provide some clarification on this matter.

**Comment by liuxiyang641** [comment]
Yes, the performance of RAGAT reported in Table 2 is evaluated using `ont-to-n` strategy.

**Comment by parsa-abbasi** [comment]
Thanks 🙏
