### ISSUE TITLE
WN18RR训练问题

### ISSUE THREAD

**Issue by hanwenhao369** [liuxiyang641/RAGAT#14]
你好，请问为什么我在FB15K-237上训练时收敛的很快，而且效果也不错，但在WN18RR上训练效果很差，几乎不收敛，MRR一直在0.0几是怎么回事呢？

**Comment by liuxiyang641** [comment]
你好，现在的代码对于FB25k-237和WN18RR是通用的，两个数据集只有在超参上有区别。
在WN18RR上训练表现出来的没有收敛的情况，RAGAT的代码是在COMPGCN方法的开源代码上改进的，我建议可以尝试下COMPGCN对于WN18RR的训练效果。
