### ISSUE TITLE
评分函数只能使用ConvE或InteractE吗？

### ISSUE THREAD

**Issue by BeJoyfulxc** [liuxiyang641/RAGAT#16]
您的代码里除了ConvE或InteractE，还有transE和distmult这两种评分函数，但是论文没有使用这两种评分函数的训练结果，我尝试使用语句python run.py -epoch 200 -name test_wn -model ragat -score_func transe -data WN18RR -batch 256 -opn mult
运行run.py，但是报错了，请问代码里的这两个评分函数是不可用的吗？

报错如下：
```
2024-01-03 15:30:18,544 - [DEBUG] - <class 'Exception'>____forward() takes 3 positional arguments but 4 were given
traceback.format_exc():____Traceback (most recent call last):
  File "run.py", line 448, in fit
    train_loss = self.run_epoch(epoch, val_mrr)
  File "run.py", line 410, in run_epoch
    pred = self.model.forward(sub, rel, neg_ent)
TypeError: forward() takes 3 positional arguments but 4 were given

```

**Comment by liuxiyang641** [comment]
你好，这个项目是基于[COMPCN](https://github.com/malllabiisc/CompGCN)代码编写的，我之前主要是用ConvE这种效果比较好的打分函数进行实验。因此transE和distmult这两种评分函数并没有实际测试过是否能够正确运行。
不过这两个函数本身的逻辑应该是正确的，在修改输入和输出的代码之后，应该可以正确使用。

**Comment by BeJoyfulxc** [comment]
好的，谢谢您！
