### ISSUE TITLE
关于模型的架构

### ISSUE THREAD

**Issue by code-gamer** [liuxiyang641/RAGAT#17]
您好，您说RAGAT项目基于COMGCN，那么它和KBGAT有什么关系呢或者说类似的地方？我看见有其他的issue提到您在baseline中没有加入KBGAT的原因。
    同时，是否可以将decoder和encoder拆分进行使用？我想理论上应该可以，但我想听听您的意见，谢谢。

**Comment by liuxiyang641** [comment]
你好，
- RAGAT方法和KBGAT方法最大的相同点就是都用了图注意力GAT，只不过KBGAT的初始版本实现存在问题，所以没有和KBGAT进行比较。RAGAT方法在聚合邻居实体和关系embedding的时候，尝试了不同的操作，比如相乘、循环卷积、向量拼接等。
- decoder当然是可以和encoder分开使用的，encoder只是获取到了entity和relation的embedding，至于怎么使用embedding进行打分预测，是decoder的工作。可以使用任意基于embedding的打分函数作为decoder。

**Comment by code-gamer** [comment]
好的，我明白了，感谢回答。
