### ISSUE TITLE
关于训练参数“strategy”的具体含义

### ISSUE THREAD

**Issue by code-gamer** [liuxiyang641/RAGAT#18]
你好，源代码中有一个“strategy”的参数，有两种已实现方案，一种是“one_to_x”，另一种是“one_to_n”，这俩中训练策略的具体含义是什么呢？我整体浏览了源代码，但除了开始提示说是“训练策略”，其他地方没有找到提示信息，我没能通过代码看出来，能解释一下吗，谢谢。

**Comment by liuxiyang641** [comment]
你好，这两种策略我记得应该是在ConvE方法的原始实现里有的。
`one_to_x`应该是指一个正样例，即正确的尾实体，和`x`个采样的负样例，即错误的尾实体。
`one_to_n`应该是指一个正样例，和数据集内全部的`n`个实体作为负样例。

**Comment by code-gamer** [comment]
好的，我明白了，谢谢回答。
