### ISSUE TITLE
代码相关问题

### ISSUE THREAD

**Issue by 1FreshChen** [liuxiyang641/RAGAT#19]
学长您好，在直接点击run.py文件之后出现了之前的学长出现的相同的错误，按照您提供的代码在终端运行没有反馈，请问下如何解决该问题。
![QQ图片20240314195519](https://github.com/liuxiyang641/RAGAT/assets/163414655/7e50b04d-d598-4475-b0d4-035e5e73cbac)
![QQ图片20240314195527](https://github.com/liuxiyang641/RAGAT/assets/163414655/e202fe3f-627c-46fb-b9c2-c534e3e12ed2)

**Comment by liuxiyang641** [comment]
你好，从这个代码报错结果来看，应该是你的log文件路径没有配置正确，正确的路径里应该包括的是单个`\`，但是你的路径里出现了是重复的两个`\` `\`符号，这会导致程序无法准确找到log文件地址。或者你检查下是否在你的系统内，路径不能有`:`号？

**Comment by 1FreshChen** [comment]
我尝试了一下上面的报错可能是我移动了helper.py重构文件导致的，但是按照原来结构，helper.py文件引用了但没有得到应用，但是利用..去引用的时候会报错显示超出引用，不知道是什么原因
![QQ图片20240315104139](https://github.com/liuxiyang641/RAGAT/assets/163414655/56652fd9-0d75-493c-8b2b-1014ba48bc84)
![QQ图片20240315104144](https://github.com/liuxiyang641/RAGAT/assets/163414655/9efe0039-4bfa-443e-bda6-578a57b11f17)

**Comment by liuxiyang641** [comment]
这种情况下通常是在运行到`model.py`文件的时候，在系统当前的路径下没法找到`help.py`文件。你可以先尝试注释掉`from ..helper import *`，然后在合适的地方设置断点调试，打印下当前的路径。可以参考这个[回答](https://stackoverflow.com/questions/30669474/beyond-top-level-package-error-in-relative-import)。
另外，我发现pycharm中运行，和在终端直接运行命令行的系统当前路径似乎会不一致，不知道你是否尝试过在终端下直接输入命令运行。

**Comment by 1FreshChen** [comment]
按照您的知道运行到最后出现了之前同样的问题，提示无法识别ordered_set模块，但是我下载了ordered_set模块，库里头显示的却是ordered-set
![QQ图片20240315172617](https://github.com/liuxiyang641/RAGAT/assets/163414655/63cbca9c-01c8-4e22-979b-b9d39e45f6ad)
![QQ图片20240315172623](https://github.com/liuxiyang641/RAGAT/assets/163414655/134153be-078c-4bd1-b34f-afad47fdf3be)

**Comment by liuxiyang641** [comment]
你是不是下载错误包了，我记得有两个名字非常类似的ordered_set，你应该安装这个[依赖](https://pypi.org/project/ordered-set/)。
```bash
pip install ordered-set
```

**Comment by 1FreshChen** [comment]
包我下载了ordered-set和ordered_set两个，都显示已经满足了，缺少模块ordered_set还是存在
![Uploading QQ图片20240315214628.png…]()

**Comment by 1FreshChen** [comment]
run.py中的from helper import *没有得到引用不知道是不是必须的
![QQ图片20240315214628](https://github.com/liuxiyang641/RAGAT/assets/163414655/fc504380-033d-43e4-9a9d-79786583b855)
![QQ图片20240315214913](https://github.com/liuxiyang641/RAGAT/assets/163414655/d33a898c-1eec-4b0b-991a-f62488d2d399)

**Comment by 1FreshChen** [comment]
这个是我安装的库
![Uploading QQ图片20240315215244.png…]()

**Comment by liuxiyang641** [comment]
你是直接在conda base环境下安装的依赖吗？pip安装依赖的环境，和运行代码时激活的环境一样吗？
或者你可以尝试卸载掉两个ordered_set和ordered-set，然后重新安装？

**Comment by 1FreshChen** [comment]
不好意思学长，你说的这两个环境具体如何查看呀，我用的是pycharm，卸载掉之后安装还是缺少这个模块，而且ordered-set只有这一个，没有ordered_set这个库

**Comment by liuxiyang641** [comment]
用conda命令查看下就行呀：
```bash
conda env list
```
检查下你激活的是哪个conda环境来运行脚本的，然后检查下当前的这个环境里有没有安装好依赖。

**Comment by 1FreshChen** [comment]
我自己用的是python解释器，然后用conda解释器也是一样的报错，配置应该也都是有的

**Comment by liuxiyang641** [comment]
你是用的virtualenv虚拟环境吗？我看到你的运行截图里，命令行最前面有个`(base)`以及`(RAGAT-main)`，哪个是虚拟环境呢？

**Comment by 1FreshChen** [comment]
我用的就是默认的 这块儿环境自己也不是很了解 但是这个问题是解决了 是之前的符号问题导致的无法识别 现在运行了一点报错broken pipe
![Uploading IMG_9726.png…]()

**Comment by liuxiyang641** [comment]
你好，上传的图片我这里加载不出来
<img width="298" alt="image" src="https://github.com/liuxiyang641/RAGAT/assets/38466943/70ba1b80-a98c-45fd-be7c-b8cf45c3e8f5">
可能是你没有上传完image就点击了comment

**Comment by 1FreshChen** [comment]
![IMG_9726](https://github.com/liuxiyang641/RAGAT/assets/163414655/1c49ebd8-e976-40cd-bbb0-c4bc691082bd)

**Comment by liuxiyang641** [comment]
看起来是pytorch并发的处理输入数据的时候报错了，这个原因可能和具体的硬件环境相关。
你可以尝试在命令行把超参数`num_workers`设置为`0`或者`1`：
```bash
--num_workers 0
```
或者干脆修改代码文件里对应的默认设置

**Comment by 1FreshChen** [comment]
好的谢谢学长 初学者遇到的问题还是很多 我自己再摸索摸索

**Comment by liuxiyang641** [comment]
嗯嗯 很多问题google一下都会有答案，另外多尝试用pycharm设置断点，调试代码看看具体的运行过程会有很大帮助

**Comment by 1FreshChen** [comment]
谢谢指导
