### ISSUE TITLE
didn't find  parameter 'num_bases'

### ISSUE THREAD

**Issue by leijing000** [liuxiyang641/RAGAT#2]
Dear XIYANG LIU:
I ran your code but got an error ，the error is reported as follows：

AttributeError: 'Namespace' object has no attribute 'num_bases'

I didn't find  parameter 'num_bases', can you tell me where it is?
Looking forward to your reply!

**Comment by liuxiyang641** [comment]
Sorry, `num_bases` is an useless hyperparameter. Now it's removed and you can try run the code again.
