### ISSUE TITLE
模块识别不出

### ISSUE THREAD

**Issue by sorryhorizonTT** [liuxiyang641/RAGAT#21]
学长您好，我想请问下对于直接运行run.py文件没有产生报错，并且会执行每一个epoch并反馈出一些结果，但是在进行模型训练的时候，在终端输入命令后，出现了ordered-set模块识别不了是什么原因呢
![屏幕截图 2024-03-31 154531](https://github.com/liuxiyang641/RAGAT/assets/130207576/38748982-552d-4121-9b04-6174826b80cf)

**Comment by liuxiyang641** [comment]
这应该是因为你的环境不一致吧，检查下你用IDE运行`run.py`是用的什么环境，然后在终端下运行的时候是用的什么环境。
比如你使用`conda`环境来管理Python依赖的话，应该保证激活的是一样的环境

**Comment by sorryhorizonTT** [comment]
感谢学长的及时解答 上面的问题解决了
我还想询问1、直接运行run.py和在终端下运行的命令分别代表的是什么，我尝试运行了run.py的代码给出的结果是有关头，尾巴，平均的MRR值还有hit值，但是没有分数据集，有点不理解。
2、因为用cpu运行的太慢了，我尝试利用GPU来跑代码，查看了cuda的版本等问题均符合下载的要求，但是出现了如下图所示的错误，我想请问是硬件问题么。
![屏幕截图 2024-03-31 205516](https://github.com/liuxiyang641/RAGAT/assets/130207576/1100198b-3617-4169-bb20-58c5fe6ceaae)

**Comment by liuxiyang641** [comment]
1. 运行`run.py`最后输出的结果就是在test集上的结果，中间过程会在验证集上进行评估
2. 这就是你的GPU显存不够，所以报错out of memory了
