### ISSUE TITLE
对代码中的参数的一些疑问

### ISSUE THREAD

**Issue by corejjelyar** [liuxiyang641/RAGAT#23]
学长好，我阅读了您的文章，然后想去得到不同关系类型下的头部和尾部预测数据，但是在我运行代码时，strategy只能选择1-n当选择其他三种关系类型代码会报错，想问一下怎么获取其他关系类型的头部和尾部预测的数据呢

**Comment by liuxiyang641** [comment]
有一个简单的办法是，人工划分出来不同关系类型的测试集到不同的测试文件，然后在代码里直接指定测试文件的路径，一个个测试文件测试过去即可
