### ISSUE TITLE
No module named 'ordered_set'

### ISSUE THREAD

**Issue by Doriyz** [liuxiyang641/RAGAT#27]
I have cloned your code and run the example command  in README :

```
python run.py -epoch 1500 -name test_fb -model ragat -score_func \
interacte -opn cross -gpu 0 -data FB15k-237 -gcn_drop 0.4 -ifeat_drop 0.4 \
-ihid_drop 0.3 -batch 1024 -iker_sz 9 -attention True -head_num 2
```

but i got the following error:
```
 Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from helper import *
  File "C:\Users\Maysion\Repository\Work\RAGAT\helper.py", line 8, in <module>
    from ordered_set import OrderedSet
ModuleNotFoundError: No module named 'ordered_set'
```
I tried to solve this problem by running: `conda install ordered_set`. However, it didn't work. 
I wonder if there are other solutions. thanks much!

**Comment by liuxiyang641** [comment]
Maybe you can try run the [script](https://pypi.org/project/ordered-set/):
```bash
pip install ordered-set
```

**Comment by Doriyz** [comment]
> Maybe you can try run the [script](https://pypi.org/project/ordered-set/):
> 
> ```shell
> pip install ordered-set
> ```

Cheers! It worked for me. I really appreciate your comment!
