### ISSUE TITLE
关于嵌入

### ISSUE THREAD

**Issue by layton17** [liuxiyang641/RAGAT#28]
你好学长，我刚接触知识图谱，想利用您方法得到的实体嵌入向量做一些下游的任务，但是在输出的文件中好像没有类型的输出，可以赐教一下吗

**Comment by liuxiyang641** [comment]
你好，只需要写代码把GNN最终得到的实体embedding（也就是输入给解码器的实体embedding）保存导出即可

**Comment by layton17** [comment]
好的 谢谢
