### ISSUE TITLE
有关case study的提问

### ISSUE THREAD

**Issue by corejjelyar** [liuxiyang641/RAGAT#29]
学长您好，我想问一个和本论文无关但又很重要的一个问题。就是知识图谱补全要给出具体的示例例如：
![11](https://github.com/liuxiyang641/RAGAT/assets/166306353/5d3991dd-a011-4d6c-9991-78e3e8c446c8)
对于这样的实例，给定一个关系和关系和候选实体去得到每一个候选实体的分数，对于数据集要进行如何处理才可以得到这个结果？是要保留test文件中的给定实体和关系以及候选实体构成的三元组其余的删除然后训练吗？如果学长了解希望给点建议

**Comment by liuxiyang641** [comment]
你好，这个候选实体分数就是解码器的输出，你导出解码器的输出就能够获得对不同候选尾实体的预测分数了。然后，每个实体对应的id，是在模型开始训练前就设定好了的。你根据解码器输出的分数，去对应到不同的具体实体就行。
不需要重新训练，而是需要把训练好的模型预测结果导出。

**Comment by corejjelyar** [comment]
了解了，但是具体是怎么找出呢，以ragat为例log文件是每一个循环的知识推理数值，那解码器的最终预测我应该再哪里寻找呢

**Comment by liuxiyang641** [comment]
在代码里导出解码器输出结果对应的张量即可
