### ISSUE TITLE
代码疑惑

### ISSUE THREAD

**Issue by junkangwu** [liuxiyang641/RAGAT#3]
您好，请问计算attention时，
`powers = -self.leakyrelu(all_message.mm(att_weight).squeeze())`
激活函数前为什么有一个负号呢？如何理解呀？不加会对实验效果有影响吗？
感谢！

**Comment by liuxiyang641** [comment]
您好，`-`是为了减小由softmax函数可能带来的不稳定性，如果去掉的话应该也可以正常工作。
这一符号初始是在GAT的pytorch实现的[Sparse版本](https://github.com/Diego999/pyGAT/blob/b7b68866739fb5ae6b51ddb041e16f8cef07ba87/layers.py#L151)中使用，在KGAT模型中同样是使用了相同的实现。

**Comment by junkangwu** [comment]
好的，感谢及时回答！
