### ISSUE TITLE
参数设置问题

### ISSUE THREAD

**Issue by SsnAgo** [liuxiyang641/RAGAT#8]
作者您好！
再次打扰您了~

我运行了几次代码，但是发现各项指标结果总是和文中报告的差0.2%或0.3%左右（只运行了FB15K-237），用的是默认的以及readme.md里给的参数。请问readme.md里展示的是最佳参数吗？
看到别的issue有提到给注意力增加dropout的问题，请问是有沿用哪个模型的做法吗？想请问一下是否有做过不dropout的实验结果呢？想知道两者哪个会更好一些，大概会差多少呢？
问题有点多...还请您见谅

**Comment by liuxiyang641** [comment]
你好，时间过去的有点久，我对于具体代码的实现细节有点记不清了。但是README中的提供的超参设置应该是找到的最好结果。
至于为什么没有达到最好的效果，我想知道你的具体的预测结果是什么？
另外如果可以的话，也可以尝试下在WN18RR数据集下的效果。

有关注意力的相关代码，我是借鉴的KBGAT的[代码](https://github.com/lovishmadaan/kbgat)。如果不给attention增加dropout，效果的变化，我无法给出准确的答案，还是建议自己做一下实验看一下。另外根据我的一点经验，dropout的设置是否有效，结果不一定是通用的，还是在自己的实验中都尝试下比较合理。

**Comment by SsnAgo** [comment]
@liuxiyang641 好滴，了解了，谢谢您的及时回复！
