### ISSUE TITLE
关于模型的保存与读取

### ISSUE THREAD

**Issue by EurusNotes** [liuxiyang641/RAGAT#9]
您好，不好意思，有几个问题想请教一下。
想询问如何保存学习过后的模型，以及如何读取保存的模型。
我试着跑了一下模型，MRR之类的结果是可以输出的。
关于详细的预测结果的输出，这一部分应该是需要自己加的吧？

**Comment by liuxiyang641** [comment]
你好，模型本身的参数在训练过程中达到最好结果的时候会自动保存在`checkpoints/`文件夹下，如果后续使用可以通过命令行参数`-restore`和`-name checkpoints下的对应文件名`来重新加载特定的模型参数；
如果希望更改输出的评估指标的结果，可以自己通过修改`run.py`文件中的`evaluate()`函数进行变动。

**Comment by EurusNotes** [comment]
谢谢您的回复！
